branches:
  only:
    - master
version: '{build}'
image:
  - Visual Studio 2019
cache:
  - "%LocalAppData%\\NuGet\\Cache"
  - "%LocalAppData%\\NuGet\\v3-cache"
build_script:
  - ps: .\build.cmd CI
test: off
