branches:
  only:
    - master
version: '{build}'
os: Windows Server 2012
cache:
  - "%LocalAppData%\\NuGet\\Cache"
  - "%LocalAppData%\\NuGet\\v3-cache"
build_script:
  - ps: .\build.cmd CI
test: off
